#!/usr/bin/env bash

if [ "$TARGET" = "browser" ]; then
  ./node_modules/.bin/browserify spec/client.js -t babelify | node_modules/.bin/tape-run
  exit $?
fi

if [ "$TARGET" = "node" ]; then
  ./node_modules/.bin/babel-node spec/server.js
  exit $?
fi

if [ "$1" = "--watch" ]; then
  ./node_modules/.bin/chokidar './src/**/*.js' './spec/**/*.js' -c './scripts/test'
else
  set -o pipefail
  echo "NODE:"
  ./node_modules/.bin/babel-node spec/server.js | node_modules/.bin/tap-spec
  if [ $? -eq 0 ]; then
    echo "BROWSER:"
    ./node_modules/.bin/browserify spec/client.js -d -t babelify | node_modules/.bin/tape-run | node_modules/.bin/tap-spec
  fi
fi

exit $?
